# Generated by Django 3.2.9 on 2021-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('sana', models.DateField()),
                ('jins', models.CharField(choices=[('e', 'erkak'), ('a', 'ayol')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('yil', models.DateField()),
                ('imbd', models.DecimalField(decimal_places=1, max_digits=3)),
                ('janr', models.CharField(max_length=50)),
                ('actor', models.ManyToManyField(to='nextapp.Actor')),
            ],
        ),
    ]
